import { QueryClientProvider } from "@tanstack/react-query";
import { createRouter, RouterProvider } from "@tanstack/react-router";
import { ThemeProvider } from "next-themes";
import * as React from "react";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { setupGlobalErrorHandlers } from "@/lib/errorLogger";
import { queryClient } from "@/lib/react-query";
import { routeTree } from "@/routeTree.gen"; // This is generated by TanStack Router Vite plugin

// Initialize global error handlers on app start
setupGlobalErrorHandlers();

/**
 * Create a new router instance with React Query context
 * Configured for optimal preloading strategy with React Query
 */
const router = createRouter({
	routeTree,
	context: {
		queryClient,
	},
	defaultPreload: "intent",
	// Since we're using React Query, we don't want loader calls to ever be stale
	// This will ensure that the loader is always called when the route is preloaded or visited
	defaultPreloadStaleTime: 0,
});

// Register the router instance for type safety
declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router;
	}
}

interface AppProviderProps {
	children?: React.ReactNode;
}

/**
 * AppProvider - Root provider component
 * Wraps application with necessary providers and error boundaries
 *
 * Includes:
 * - Error Boundary for component errors
 * - Theme Provider for light/dark mode
 * - React Query for data fetching
 * - TanStack Router for routing
 * - Global error handler initialization
 */
export function AppProvider({ children }: AppProviderProps) {
	return (
		<ErrorBoundary>
			<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
				<QueryClientProvider client={queryClient}>
					<React.Suspense
						fallback={
							<div className="flex min-h-screen items-center justify-center text-sm text-muted-foreground">
								Loading page...
							</div>
						}
					>
						<RouterProvider router={router} />
					</React.Suspense>
					{children}
				</QueryClientProvider>
			</ThemeProvider>
		</ErrorBoundary>
	);
}
